### ISSUE TITLE
Long and inconsistent loading times with some SVG images

### ISSUE THREAD

**Issue by DZ-cadwin** [weisJ/jsvg#178]
We've tried to benchmark JSVG (up-to-date 2.2.0 of course) versus our preexisting Batik SVG rendering tool. 

In order to test extensively, we've duplicated the test file and are loading it multiple times in a row (extracting the content into a String first in order to remove the file parsing delay and get only the raw rendering time). 

Batik seems to take longer for the first loading, then the subsequent ones take a fraction of that delay. 

JSVG seems to be inconsistent from one loading to another, ranging from a few dozen milliseconds to hundreds of milliseconds. And this not just with a longer first loading and shorter ones, but varying between the second, third and fourth loading.

Also, the "No Text" version seems to consistently require close or higher than one second of loading (again, dependent on machine performance on our side, but the Batik renderer takes half that time on the first loading, then a few dozen milliseconds on the subsequent loadings within the same benchmark).

Are we in a specific case in which JSVG's performance can be improved?
 
Note that our renderers use the centering calculations mentioned in Issue #156 (with some code accomplishing the same thing in the Batik renderer) in order to display only the smallest non-empty rectangle in the image.

Here are some of the images for which we found significant gaps and inconsistencies, if further analysis is needed.
 

[Test images.zip](https://github.com/user-attachments/files/32374352/Test.images.zip)

<img width="179" height="150" alt="Image" src="https://github.com/user-attachments/assets/260f9fe2-7fc0-4059-9787-c75ae9279883" />
<img width="179" height="150" alt="Image" src="https://github.com/user-attachments/assets/eaa7fc4d-16f7-41dd-b484-b8965e2b9a24" />

**Comment by weisJ** [comment]
Could you share more details about your benchmark setup and the results you got? The parsing is completely deterministic, so varying timings highly indicate that testing is also influenced by other external factors (e.g other processes). Without seeing your exact setup I cannot say much more.

**Comment by DZ-cadwin** [comment]
Here are the two renderers we're using for rendering the SVG Strings (simplified in order to remove some of our in-house dependences) : 
 
[BatikRendererStandard.java](https://github.com/user-attachments/files/32381968/BatikRendererStandard.java)
[JSVGRendererStandard.java](https://github.com/user-attachments/files/32381976/JSVGRendererStandard.java)

The benchmarks do, per run, 5 copies of the two attached SVG files. They begin by parsing the files in order to obtain Strings, then render one by one.

**Comment by DZ-cadwin** [comment]
Benchmark results (one run but quite representative of the other runs we made) : 

Batik 

> Original - Copy (3).svg.<<< done in 0.487 s
> NoText - Copy (2).svg.<<< done in 0.514 s
> Original - Copy (4).svg.<<< done in 0.041 s
> NoText.svg.<<< done in 0.056 s
> NoText - Copy (4).svg.<<< done in 0.094 s
> NoText - Copy.svg.<<< done in 0.030 s
> Original - Copy.svg.<<< done in 0.039 s
> NoText - Copy (3).svg.<<< done in 0.028 s
> Original.svg.<<< done in 0.056 s
> Original - Copy (2).svg.<<< done in 0.055 s
> Total renderings <<< done in 1.408 s

JSVG

> Original - Copy (3).svg.<<< done in 0.508 s
> NoText - Copy (2).svg.<<< done in 1.137 s
> Operation overran alert threshold [1.000 s]
> Copy (4).svg.<<< done in 0.376 s
> NoText.svg.<<< done in 0.355 s
> NoText - Copy (4).svg.<<< done in 0.051 s
> NoText - Copy.svg.<<< done in 0.049 s
> Original - Copy.svg.<<< done in 0.214 s
> NoText - Copy (3).svg.<<< done in 0.186 s
> Original.svg.<<< done in 0.259 s
> Original - Copy (2).svg.<<< done in 0.335 s
> Total renderings <<< done in 3.479 s

**Comment by weisJ** [comment]
Please post your actual benchmarking code. The one that produces the above output. Also please clarify: are you testing rendering speed or document parsing speed? The files above seem to indicate you are testing rendering, but the issue text talks about loading times.

**Comment by weisJ** [comment]
I did a proper benchmark using JMH (assuming you mean rendering speeds instead of parsing).

<details><summary>Bechmark code</summary>

````java
package com.github.weisj.jsvg.benchmark;

import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.AffineTransform;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.Objects;
import java.util.concurrent.TimeUnit;

import org.apache.batik.bridge.BridgeContext;
import org.apache.batik.bridge.DocumentLoader;
import org.apache.batik.bridge.GVTBuilder;
import org.apache.batik.bridge.UserAgent;
import org.apache.batik.bridge.UserAgentAdapter;
import org.apache.batik.gvt.GraphicsNode;
import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Fork;
import org.openjdk.jmh.annotations.Level;
import org.openjdk.jmh.annotations.Measurement;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Param;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.openjdk.jmh.annotations.TearDown;
import org.openjdk.jmh.annotations.Threads;
import org.openjdk.jmh.annotations.Warmup;
import org.w3c.dom.Document;

import com.github.weisj.jsvg.SVGDocument;
import com.github.weisj.jsvg.parser.SVGLoader;

@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
@Warmup(iterations = 5, time = 500, timeUnit = TimeUnit.MILLISECONDS)
@Measurement(iterations = 8, time = 500, timeUnit = TimeUnit.MILLISECONDS)
@Fork(value = 3, jvmArgsAppend = "-Djava.awt.headless=true")
@Threads(1)
public class Issue178Benchmark {

    /**
     * Render Batik's prepared GVT. {@link GraphicsNode#getBounds()} caches its result.
     */
    @Benchmark
    public void batik(BenchmarkState state) {
        Rectangle2D bounds = requireBounds(state.batikGraphicsNode.getBounds());
        state.paintBatik(transformToFit(bounds));
    }

    /**
     * Render JSVG after computing the exact painted shape used by the issue reporter.
     */
    @Benchmark
    public void jsvg(BenchmarkState state) {
        Rectangle2D bounds = state.jsvgDocument.computeShape().getBounds2D();
        state.paintJsvg(transformToFit(bounds));
    }

    /**
     * Render JSVG using exact painted bounds computed before the benchmark begins.
     */
    @Benchmark
    public void jsvgCachedBounds(BenchmarkState state) {
        state.paintJsvg(transformToFit(state.cachedJsvgBounds));
    }

    /**
     * Render JSVG after computing conservative bounds without constructing an exact shape union.
     */
    @Benchmark
    public void jsvgComputeBounds(BenchmarkState state) {
        state.paintJsvg(transformToFit(state.jsvgDocument.computeBounds()));
    }

    private static Rectangle2D requireBounds(Rectangle2D bounds) {
        return Objects.requireNonNull(bounds, "SVG has no drawable bounds");
    }

    private static AffineTransform transformToFit(Rectangle2D bounds) {
        double scale = Math.min(BenchmarkState.WIDTH / bounds.getWidth(), BenchmarkState.HEIGHT / bounds.getHeight())
                / 1.1;
        double renderedWidth = bounds.getWidth() * scale;
        double renderedHeight = bounds.getHeight() * scale;
        double x = -bounds.getX() * scale + (BenchmarkState.WIDTH - renderedWidth) / 2;
        double y = -bounds.getY() * scale + (BenchmarkState.HEIGHT - renderedHeight) / 2;
        return new AffineTransform(scale, 0, 0, scale, x, y);
    }

    @State(Scope.Thread)
    public static class BenchmarkState {

        private static final int WIDTH = 179;
        private static final int HEIGHT = 150;
        private static final String RESOURCE_ROOT = "/com/github/weisj/jsvg/benchmark/issue178/";
        private static final RenderingHints RENDERING_HINTS =
                new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_SPEED);

        @Param({"NoText.svg", "Original.svg"})
        public String asset;

        private SVGDocument jsvgDocument;
        private Rectangle2D cachedJsvgBounds;
        private BatikSession batikSession;
        private GraphicsNode batikGraphicsNode;
        private BufferedImage target;
        private Graphics2D graphics;

        @Setup(Level.Trial)
        public void setUpTrial() throws IOException {
            URL resource = Objects.requireNonNull(
                    Issue178Benchmark.class.getResource(RESOURCE_ROOT + asset), "Missing benchmark asset " + asset);

            jsvgDocument = Objects.requireNonNull(new SVGLoader().load(resource), "JSVG failed to parse " + asset);
            cachedJsvgBounds = jsvgDocument.computeShape().getBounds2D();
            verifyContainsExactBounds(jsvgDocument.computeBounds(), cachedJsvgBounds);

            batikSession = new BatikSession();
            Document batikDocument = batikSession.loader.loadDocument(resource.toExternalForm());
            batikGraphicsNode = new GVTBuilder().build(batikSession.context, batikDocument);
            batikGraphicsNode.setRenderingHints(RENDERING_HINTS);

            target = new BufferedImage(WIDTH, HEIGHT, BufferedImage.TYPE_INT_ARGB);
        }

        private static void verifyContainsExactBounds(Rectangle2D bounds, Rectangle2D exactBounds) {
            double epsilon = 1e-3;
            Rectangle2D expandedBounds = new Rectangle2D.Double(
                    bounds.getX() - epsilon,
                    bounds.getY() - epsilon,
                    bounds.getWidth() + 2 * epsilon,
                    bounds.getHeight() + 2 * epsilon);
            if (!expandedBounds.contains(exactBounds)) {
                throw new IllegalStateException(
                        "Computed bounds " + bounds + " do not contain exact bounds " + exactBounds);
            }
        }

        @Setup(Level.Invocation)
        public void setUpInvocation() {
            graphics = target.createGraphics();
            graphics.setComposite(AlphaComposite.Clear);
            graphics.fillRect(0, 0, WIDTH, HEIGHT);
            graphics.setComposite(AlphaComposite.SrcOver);
        }

        @TearDown(Level.Invocation)
        public void tearDownInvocation() {
            graphics.dispose();
        }

        @TearDown(Level.Trial)
        public void tearDownTrial() {
            batikSession.close();
        }

        private void paintJsvg(AffineTransform transform) {
            graphics.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_SPEED);
            graphics.transform(transform);
            jsvgDocument.render(null, graphics);
        }

        private void paintBatik(AffineTransform transform) {
            graphics.transform(transform);
            batikGraphicsNode.paint(graphics);
        }
    }

    private static final class BatikSession implements AutoCloseable {

        private final DocumentLoader loader;
        private final BridgeContext context;

        private BatikSession() {
            UserAgent userAgent = new UserAgentAdapter();
            loader = new DocumentLoader(userAgent);
            context = new BridgeContext(userAgent, loader);
        }

        @Override
        public void close() {
            context.dispose();
            loader.dispose();
        }
    }
}
````
</details>

## Results
````
Benchmark                                 (asset)  Mode  Cnt    Score   Error  Units
Issue178Benchmark.batik                NoText.svg  avgt   24    0,203 ± 0,002  ms/op
Issue178Benchmark.batik              Original.svg  avgt   24    0,709 ± 0,044  ms/op
Issue178Benchmark.jsvg                 NoText.svg  avgt   24   78,990 ± 1,161  ms/op
Issue178Benchmark.jsvg               Original.svg  avgt   24  138,806 ± 1,891  ms/op
Issue178Benchmark.jsvgCachedBounds     NoText.svg  avgt   24    0,163 ± 0,001  ms/op
Issue178Benchmark.jsvgCachedBounds   Original.svg  avgt   24    0,671 ± 0,008  ms/op
Issue178Benchmark.jsvgComputeBounds    NoText.svg  avgt   24    0,652 ± 0,004  ms/op
Issue178Benchmark.jsvgComputeBounds  Original.svg  avgt   24    1,357 ± 0,013  ms/op
````

The most expensive part in your JSVG code is the `computeShape()` call. Its result (as opposed to Batik's `getBounds()`) is not cached. Computing the exact shape of the output image is rather expensive. The `Issue178Benchmark.jsvgCachedBounds` tests rendering with a cached result for `computeShape().getBounds2D()`.
I have also added a benchmark for a custom `Output` implementation that just accumulates the bounds instead of the full shape (see `Issue178Benchmark.jsvgComputeBounds`). Here is the implementation of that class.

<details><summary>BoundOutput.java</summary>

````java
public class BoundOutput implements Output {

    private final @NotNull BoundsAccumulator accumulator;
    private @NotNull AffineTransform currentTransform;
    private @NotNull Stroke currentStroke;
    private @Nullable Rectangle2D currentClip;

    public BoundOutput() {
        accumulator = new BoundsAccumulator();
        currentStroke = new BasicStroke();
        currentTransform = new AffineTransform();
        currentClip = null;
    }

    private BoundOutput(@NotNull BoundOutput parent) {
        accumulator = parent.accumulator;
        currentStroke = parent.currentStroke;
        currentTransform = new AffineTransform(parent.currentTransform);
        currentClip = copyNullable(parent.currentClip);
    }

    /**
     * Returns the accumulated bounds. An empty rectangle is returned if no content was painted.
     */
    public @NotNull Rectangle2D bounds() {
        return accumulator.bounds();
    }

    private void addShape(@NotNull Shape shape) {
        addBounds(transformedBounds(shape, currentTransform));
    }

    private void addShape(@NotNull Shape shape, @NotNull AffineTransform transform) {
        AffineTransform combinedTransform = new AffineTransform(currentTransform);
        combinedTransform.concatenate(transform);
        addBounds(transformedBounds(shape, combinedTransform));
    }

    private void addBounds(@NotNull Rectangle2D bounds) {
        if (currentClip != null) {
            bounds = currentClip.createIntersection(bounds);
        }
        accumulator.add(bounds);
    }

    private static @NotNull Rectangle2D transformedBounds(
            @NotNull Shape shape, @NotNull AffineTransform transform) {
        return copy(GeometryUtil.containingBoundsAfterTransform(transform, shape.getBounds2D()));
    }

    private static @NotNull Rectangle2D copy(@NotNull Rectangle2D bounds) {
        return new Rectangle2D.Double(bounds.getX(), bounds.getY(), bounds.getWidth(), bounds.getHeight());
    }

    private static @Nullable Rectangle2D copyNullable(@Nullable Rectangle2D bounds) {
        return bounds != null ? copy(bounds) : null;
    }

    @Override
    public void fillShape(@NotNull Shape shape) {
        addShape(shape);
    }

    @Override
    public void drawShape(@NotNull Shape shape) {
        addShape(currentStroke.createStrokedShape(shape));
    }

    @Override
    public void drawImage(@NotNull BufferedImage image) {
        addShape(new Rectangle2D.Float(0, 0, image.getWidth(), image.getHeight()));
    }

    @Override
    public void drawImage(@NotNull Image image, @Nullable ImageObserver observer) {
        addShape(new Rectangle2D.Float(0, 0, image.getWidth(observer), image.getHeight(observer)));
    }

    @Override
    public void drawImage(@NotNull Image image, @NotNull AffineTransform at, @Nullable ImageObserver observer) {
        addShape(new Rectangle2D.Float(0, 0, image.getWidth(observer), image.getHeight(observer)), at);
    }

    @Override
    public void setPaint(@NotNull Paint paint) {
        // Not supported. Do nothing
    }

    @Override
    public void setPaint(@NotNull Supplier<Paint> paintProvider) {
        // Not supported. Do nothing
    }

    @Override
    public void setStroke(@NotNull Stroke stroke) {
        currentStroke = stroke;
    }

    @Override
    public @NotNull Stroke stroke() {
        return currentStroke;
    }

    @Override
    public void applyClip(@NotNull Shape clipShape) {
        Rectangle2D transformedClip = transformedBounds(clipShape, currentTransform);
        currentClip = currentClip != null
                ? currentClip.createIntersection(transformedClip)
                : transformedClip;
    }

    @Override
    @Deprecated
    public void setClip(@Nullable Shape shape) {
        currentClip = shape != null ? transformedBounds(shape, currentTransform) : null;
    }

    @Override
    public Optional<Float> contextFontSize() {
        return Optional.empty();
    }

    @Override
    public @NotNull Output createChild() {
        return new BoundOutput(this);
    }

    @Override
    public void dispose() {
        // No action needed
    }

    @Override
    public void debugPaint(@NotNull Consumer<Graphics2D> painter) {
        // Not supported. Do nothing
    }

    @Override
    public @NotNull Rectangle2D clipBounds() {
        float veryLargeNumber = Float.MAX_VALUE / 4;
        return currentClip != null
                ? currentClip.getBounds2D()
                : new Rectangle2D.Float(-veryLargeNumber, -veryLargeNumber, 2 * veryLargeNumber, 2 * veryLargeNumber);
    }

    @Override
    public @Nullable RenderingHints renderingHints() {
        return null;
    }

    @Override
    public @Nullable Object renderingHint(RenderingHints.@NotNull Key key) {
        return null;
    }

    @Override
    public void setRenderingHint(RenderingHints.@NotNull Key key, @Nullable Object value) {
        // Not supported. Do nothing
    }

    @Override
    public @NotNull AffineTransform transform() {
        return new AffineTransform(currentTransform);
    }

    @Override
    public void setTransform(@NotNull AffineTransform affineTransform) {
        currentTransform = new AffineTransform(affineTransform);
    }

    @Override
    public void applyTransform(@NotNull AffineTransform transform) {
        currentTransform.concatenate(transform);
    }

    @Override
    public void rotate(double angle) {
        currentTransform.rotate(angle);
    }

    @Override
    public void scale(double sx, double sy) {
        currentTransform.scale(sx, sy);
    }

    @Override
    public void translate(double dx, double dy) {
        currentTransform.translate(dx, dy);
    }

    @Override
    public float currentOpacity() {
        return 1;
    }

    @Override
    public void applyOpacity(float opacity) {
        // Not supported. Do nothing
    }

    @Override
    public @NotNull SafeState safeState() {
        return new BoundOutputSafeState(this);
    }

    @Override
    public boolean supportsFilters() {
        return false;
    }

    @Override
    public boolean supportsColors() {
        return false;
    }

    @Override
    public boolean isSoftClippingEnabled() {
        // Not needed here. Always return false
        return false;
    }

    private static class BoundsAccumulator {
        private @Nullable Rectangle2D bounds;

        public void add(@NotNull Rectangle2D additionalBounds) {
            if (additionalBounds.isEmpty()) return;
            if (bounds == null) {
                bounds = copy(additionalBounds);
            } else {
                bounds.add(additionalBounds);
            }
        }

        public @NotNull Rectangle2D bounds() {
            return bounds != null ? copy(bounds) : new Rectangle2D.Double();
        }
    }

    private static class BoundOutputSafeState implements SafeState {
        private final @NotNull BoundOutput output;
        private final @NotNull Stroke oldStroke;
        private final @NotNull AffineTransform oldTransform;
        private final @Nullable Rectangle2D oldClip;

        private BoundOutputSafeState(@NotNull BoundOutput output) {
            this.output = output;
            oldStroke = output.stroke();
            oldTransform = output.transform();
            oldClip = copyNullable(output.currentClip);
        }

        @Override
        public void restore() {
            output.currentStroke = oldStroke;
            output.currentTransform = oldTransform;
            output.currentClip = oldClip;
        }
    }
}
````
</details>

**Comment by DZ-cadwin** [comment]
Indeed, sorry, I might have phrased it wrong, we're interested in a performance equivalence for the [load+render] operation starting from a SVG file. Caching isn't an option since the first time has to have acceptable performance too. 
Our benchmark was flawed based on that, we're fixing the evaluation process in order to not compare multiple consecutive renderings of the same image.

The code you gave us seems to use the following method :
`com.github.weisj.jsvg.SVGDocument.computeBounds()`
for better performance (which might bridge the performance gap) compared to :
`com.github.weisj.jsvg.SVGDocument.computeShape().getBounds2D()`

However, the _computeBounds_ method doesn't seem to be present in JSVG 2.2's _SVGDocument_ class doesn't have such a method. Is it part of the 2.3 staging code?

**Comment by weisJ** [comment]
> However, the computeBounds method doesn't seem to be present in JSVG 2.2's SVGDocument class doesn't have such a method. Is it part of the 2.3 staging code?

I forgot to update the code example. The method is not yet available anywhere, but the implementation is just to render using `new BoundOutput()` and then calling `bounds()` on it. I am still on the fence whether I want to add it to the public API.

**Comment by DZ-cadwin** [comment]
Not sure what "render using new BoundOutput()" would look like in terms of code. What would it look like in your benchmark example? How would it be invoked? (so that we can transpose this to our JSVGRenderer for testing)

**Comment by weisJ** [comment]
````Java
BoundOutput out = new BoundOutput();
document.render(NullPlatformSupport.INSTANCE, out, null);
Rectangle2D bounds = out.bounds();
````

**Comment by DZ-cadwin** [comment]
This code might come from a version which has a method with the following prototype :
SVGDocument.render(PlatformSupport, Output,Graphics)
It doesn't compile with JSVG 2.2 because its SVGDocument class only has the following render methods : 

   ```
 public void render(
                       @Nullable JComponent component,
                       @NotNull Graphics2D g) {
    }

    public void render(
                       @Nullable Component component,
                       @NotNull Graphics2D graphics2D,
                       @Nullable ViewBox bounds) {
    }
```

Resulting in a compilation error (more precisely, "incompatible types: NullPlatformSupport cannot be converted to Component" in case you need it).

Should the code snippet you gave us work with 2.2?
